"""The single-step vector suite: its pin, and what it says about our table.

DESIGN.md decision 4 -- the vectors themselves are third-party data,
fetched by tools/fetch_vectors.py and NEVER committed. What IS
committed is tools/vectors.lock: the pinned SHA, file census, and
license. These tests run entirely off the lock file, so they are green
on a machine that has never fetched a byte.

WHY THE LOCK IS PINNED AT ALL. Upstream is live and its tests get
corrected over time -- the pinned commit's own message is "Re-generate
the tests." Without a pin, a passing suite is unreproducible and an
upstream correction is indistinguishable from one of our regressions.
A lock bump is therefore its own deliberate commit.

THE CROSS-CHECK THIS PINS. z80/table.py was built in Phase A from the
documented x/y/z/p/q decomposition of the instruction space, with no
reference to this suite. The suite was generated by translating Ares'
Z80 core. They agree EXACTLY -- page for page, 1604 encodings, zero
uncovered on our side and zero unmatched on theirs. That is
independent corroboration of FINDING 1's table in the same spirit as
the anchors' terminating-RET check: two unrelated derivations of the
Z80 instruction space landing on the same set.

The 176 entries our table marks 'invalid' are all on the ED page, and
are exactly the ED opcodes upstream ships no tests for.

CYCLE COSTS ARE STILL UNVALIDATED HERE. This file pins the SHAPE of
the agreement (which encodings exist), not the SEMANTICS (what they
do). FINDING 1's open item -- the unvalidated cycle-cost column --
closes when the core actually runs these vectors, not before. Nothing
in this file should be read as validating execution.
"""

import json
import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from z80.table import TABLE                                  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOCK = os.path.join(ROOT, 'tools', 'vectors.lock')
V1 = os.path.join(ROOT, 'tests', 'vectors', 'v1')

# Upstream's census, page by page. Hardcoded on purpose: this is the
# pinned fact, and a silent drift in either direction should fail here.
UPSTREAM_CENSUS = {
    'main': 252,      # 256 less the four prefix bytes CB/DD/ED/FD
    'cb': 256,
    'dd': 252,        # likewise less DD CB/DD/ED/FD continuations
    'ed': 80,         # the only page that is sparse
    'fd': 252,
    'ddcb': 256,
    'fdcb': 256,
}
UPSTREAM_TOTAL = sum(UPSTREAM_CENSUS.values())      # 1604


def page_of_encoding(enc):
    if len(enc) == 1:
        return 'main'
    if len(enc) == 3:
        return {0xDD: 'ddcb', 0xFD: 'fdcb'}[enc[0]]
    return {0xCB: 'cb', 0xDD: 'dd', 0xED: 'ed', 0xFD: 'fd'}[enc[0]]


class TestLock(unittest.TestCase):
    """The pin itself -- committed metadata, no network, no data."""

    def setUp(self):
        self.assertTrue(os.path.exists(LOCK), 'tools/vectors.lock is missing')
        with open(LOCK) as f:
            self.lock = json.load(f)

    def test_lock_is_complete(self):
        for key in ('repo', 'url', 'sha', 'pinned_date', 'license',
                    'file_count', 'total_bytes', 'cases_per_file'):
            self.assertIn(key, self.lock)

    def test_sha_is_a_full_commit_id(self):
        sha = self.lock['sha']
        self.assertEqual(len(sha), 40)
        int(sha, 16)                      # raises if not hex

    def test_license_is_recorded_and_permissive(self):
        # Recorded so the never-commit rule is a choice, not an accident.
        self.assertEqual(self.lock['license'], 'MIT')

    def test_census_matches_the_pinned_file_count(self):
        self.assertEqual(self.lock['file_count'], UPSTREAM_TOTAL)

    def test_vectors_are_not_committed(self):
        """DESIGN.md decision 4, enforced rather than trusted."""
        import subprocess
        out = subprocess.run(
            ['git', 'ls-files', 'tests/vectors'],
            cwd=ROOT, capture_output=True, text=True).stdout.strip()
        self.assertEqual(out, '', 'vector data is tracked by git: %r' % out)


class TestTableAgreesWithUpstream(unittest.TestCase):
    """Two independent derivations of the Z80 instruction space, compared."""

    def setUp(self):
        self.real = {e for e in TABLE if TABLE[e].kind != 'invalid'}
        self.invalid = {e for e in TABLE if TABLE[e].kind == 'invalid'}

    def test_non_invalid_count_equals_upstream_file_count(self):
        self.assertEqual(len(self.real), UPSTREAM_TOTAL)

    def test_page_census_matches_page_for_page(self):
        got = {}
        for enc in self.real:
            k = page_of_encoding(enc)
            got[k] = got.get(k, 0) + 1
        self.assertEqual(got, UPSTREAM_CENSUS)

    def test_every_invalid_entry_is_on_the_ed_page(self):
        self.assertEqual({page_of_encoding(e) for e in self.invalid}, {'ed'})
        self.assertEqual(len(self.invalid), 256 - UPSTREAM_CENSUS['ed'])

    def test_bare_prefix_bytes_are_not_standalone_encodings(self):
        for b in (0xCB, 0xDD, 0xED, 0xFD):
            self.assertNotIn((b,), TABLE)
            self.assertNotIn((0xDD, b), TABLE)
            self.assertNotIn((0xFD, b), TABLE)


class TestFilenameMapping(unittest.TestCase):
    """Upstream filenames -> our encoding keys."""

    def test_name_to_encoding(self):
        from tools.fetch_vectors import name_to_encoding
        self.assertEqual(name_to_encoding('00.json'), (0x00,))
        self.assertEqual(name_to_encoding('cb 7e.json'), (0xCB, 0x7E))
        self.assertEqual(name_to_encoding('ed 40.json'), (0xED, 0x40))
        # '__' is upstream's placeholder for the DDCB displacement byte,
        # which is runtime data, not part of the encoding.
        self.assertEqual(name_to_encoding('dd cb __ 06.json'), (0xDD, 0xCB, 0x06))
        self.assertEqual(name_to_encoding('fd cb __ 06.json'), (0xFD, 0xCB, 0x06))

    def test_every_mapped_name_hits_a_real_table_entry(self):
        from tools.fetch_vectors import name_to_encoding
        for name in ('00.json', 'cb 7e.json', 'ed 40.json',
                     'dd cb __ 06.json', 'fd 21.json'):
            enc = name_to_encoding(name)
            self.assertIn(enc, TABLE)
            self.assertNotEqual(TABLE[enc].kind, 'invalid')


class TestFetchedVectorShape(unittest.TestCase):
    """Runs only if vectors have been fetched; skips cleanly otherwise.

    Same pattern as the anchor tests: local-only material never turns
    the suite red on a machine that does not have it.
    """

    @classmethod
    def setUpClass(cls):
        if not os.path.isdir(V1):
            raise unittest.SkipTest(
                'no fetched vectors (run tools/fetch_vectors.py --pages main)')
        cls.files = sorted(n for n in os.listdir(V1) if n.endswith('.json'))
        if not cls.files:
            raise unittest.SkipTest('tests/vectors/v1 is empty')

    def test_sampled_file_has_the_documented_shape(self):
        path = os.path.join(V1, self.files[0])
        with open(path) as f:
            cases = json.load(f)
        self.assertIsInstance(cases, list)
        self.assertEqual(len(cases), 1000)
        c = cases[0]
        for key in ('name', 'initial', 'final', 'cycles'):
            self.assertIn(key, c)
        for reg in ('pc', 'sp', 'a', 'f', 'ix', 'iy', 'wz', 'q', 'p', 'ram'):
            self.assertIn(reg, c['initial'])

    def test_fetched_names_all_map_into_the_table(self):
        from tools.fetch_vectors import name_to_encoding
        for name in self.files:
            enc = name_to_encoding(name)
            self.assertIn(enc, TABLE, 'no table entry for vector %r' % name)


if __name__ == '__main__':
    unittest.main()
